# Generated by Django 2.2.1 on 2019-07-21 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_friendship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
