# Generated by Django 2.2.1 on 2019-07-21 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_friend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
